name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install backend dependencies
        run: npm ci --prefix backend

      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Build project
        run: npm run build

      - name: Run linting (frontend)
        run: |
          if [ -f "frontend/package.json" ] && grep -q "lint" frontend/package.json; then
            npm run lint --prefix frontend
          else
            echo "No linting script found in frontend"
          fi

      - name: Run tests
        run: |
          # Run tests if they exist and are not the default "no test specified" script
          if grep -q "test" package.json && ! grep -q '"test": "echo \\"Error: no test specified\\" && exit 1"' package.json; then
            npm test
          else
            echo "No tests configured"
          fi
